apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: elb-requestscount-1min
  labels:
    app: skale
spec:
  name: elb-requestscount-1min
  resource:
    resource: "deployment"
  queries:
    - id: elb_requestscount_1min
      metricStat:
        metric:
          namespace: "AWS/ApplicationELB"
          metricName: "RequestCount"
          dimensions:
            - name: LoadBalancer
              value: "app/789e9218-towerdev-fronting-019e/f00ff4ad912d92e3 "
        period: 60
        stat: Sum
        unit: Count
      returnData: true
---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2beta1
metadata:
  name: skale
  labels:
    app: skale
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 8
  metrics:
    - type: External
      external:
        metricName: elb-requestscount-1min
        targetAverageValue: 150
