- Name: "`orgId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Organization numeric identifier.
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: The workspace name to validate for availability and format
    compliance within the organization.
- Name: "`workspaceId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Workspace numeric identifier.
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Maximum number of results to return. Default: `50`."
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Free-text search filter to match against participant names and
    email addresses.
- Name: "`participantId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Participant numeric identifier.
- Name: "`userId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: User numeric identifier.
