- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier
- Name: "`platformId`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Platform string identifier
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Credentials name to validate
- Name: "`credentialsId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Credentials string identifier
- Name: "`checked`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: If set credentials deletion will be blocked by running jobs that
    depend on them
