- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier. When omitted, Studios are listed in
    the user context.
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Free-text search filter to match against Studio `name` and
    `templateUrl`. Supports keyword filters for `userId` (Studio creator) and
    `status` (current Studio status).
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Maximum number of results to return. Default: `100`."
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`attributes`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: "Optional attribute values to be included in the response. Supports
    `labels`. Returns an empty value (`labels: null`) if omitted."
- Name: "`autoStart`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: "If true, automatically starts the Studio after creation. Default: `true`."
- Name: "`orgId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Organization numeric identifier. When specified, lists mounted
    data-links in the organization context.
- Name: "`status`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Studio status filter. Filters mounted data-links by the status of
    the Studios they are mounted in.
- Name: "`exclude`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Studio session ID to exclude from the mounted data-links list.
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Studio name to validate for availability.
- Name: "`sessionId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Studio session string identifier.
- Name: "`checkpointId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Checkpoint numeric identifier.
