- Name: "`status`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter by compute environment status.
- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier. If omitted, lists compute
    environments in a user context.
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Compute environment name to validate for uniqueness and format.
- Name: "`computeEnvId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Compute environment alphanumeric identifier.
- Name: "`attributes`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: "Additional attribute values to include in the response. Returns
    `labels: null` if omitted."
