organizations:
  - name: 'your-organization'
    full-name: 'Your organization LLC'
    description: 'Organization created E2E with seqerakit CLI scripting'
    location: 'Global'
    website: 'https://yourdomain.com/'
    overwrite: True
teams:
  - name: 'pipelines_team'
    organization: 'your-organization'
    description: 'Pipelines team @ Your organization'
    members:
      - 'user1@yourdomain.com'
      - 'user2@yourdomain.com'
      - 'user3@yourdomain.com'
    overwrite: True
workspaces:
  - name: 'workspace-1'
    full-name: 'Workspace one'
    organization: 'your-organization'
    description: 'Workspace created E2E with seqerakit CLI scripting'
    visibility: 'PRIVATE'
    overwrite: True
participants:
  - name: 'pipelines_team'
    type: 'TEAM'
    workspace: 'your-organization/workspace-1'
    role: 'ADMIN'
    overwrite: True
  - name: 'user4@domain.com@seqera.io'
    type: 'MEMBER'
    workspace: 'your-organization/workspace-1'
    role: 'LAUNCH'
    overwrite: True
credentials:
  - type: 'github'
    name: 'github_credentials'
    workspace: 'your-organization/workspace-1'
    username: 'user1'
    password: '$TOWER_GITHUB_PASSWORD'
    overwrite: True
  - type: 'container-reg'
    name: 'dockerhub_credentials'
    workspace: 'your-organization/workspace-1'
    username: 'user1'
    password: '$DOCKERHUB_PASSWORD'
    registry: 'docker.io'
    overwrite: True
  - type: 'aws'
    name: 'aws_credentials'
    workspace: 'your-organization/workspace-1'
    access-key: '$AWS_ACCESS_KEY_ID'
    secret-key: '$AWS_SECRET_ACCESS_KEY'
    assume-role-arn: '$AWS_ASSUME_ROLE_ARN'
    overwrite: True
  - type: 'azure'
    name: 'azure_credentials'
    workspace: 'your-organization/workspace-1'
    batch-key: '$AZURE_BATCH_KEY'
    batch-name: 'yourbatch'
    storage-key: '$AZURE_STORAGE_KEY'
    storage-name: 'yourstorage'
    overwrite: True
  - type: 'google'
    name: 'google_credentials'
    workspace: 'your-organization/workspace-1'
    key: '$GOOGLE_KEY'
    overwrite: True
secrets:
  - name: 'SENTIEON_LICENSE_BASE64'
    workspace: 'your-organization/workspace-1'
    value: '$SENTIEON_LICENSE_BASE64'
    overwrite: True
compute-envs:
  - name: 'your-aws-compute-environment'
    workspace: 'your-organization/workspace-1'
    credentials: 'aws_credentials'
    wait: 'AVAILABLE'
    file-path: 'path/to/aws-credentials.json'
    overwrite: True
  - name: 'your-azure-compute-environment'
    workspace: 'your-organization/workspace-1'
    credentials: 'azure_credentials'
    wait: 'AVAILABLE'
    file-path: 'path/to/azure-credentials.json'
    overwrite: True
  - name: 'your-gcp-compute-environment'
    workspace: 'your-organization/workspace-1'
    credentials: 'google_credentials'
    wait: 'AVAILABLE'
    file-path: 'path/to/gcp-credentials.json'
    overwrite: True
datasets:
  - name: 'rnaseq_samples'
    description: 'Samplesheet to run the nf-core/rnaseq pipeline end-to-end'
    header: true
    workspace: 'your-organization/workspace-1'
    file-path: 'path/to/rnaseq_samples.csv'
    overwrite: True
  - name: 'sarek_samples'
    description: 'Samplesheet to run the nf-core/sarek pipeline end-to-end'
    header: true
    workspace: 'your-organization/workspace-1'
    file-path: 'path/to/sarek_samples.csv'
    overwrite: True
  - name: 'viralrecon_illumina_samples'
    description: 'Samplesheet to run the nf-core/viralrecon pipeline from end-to-end with Illumina data'
    header: true
    workspace: 'your-organization/workspace-1'
    file-path: 'path/to/viralrecon_illumina_samples.csv'
    overwrite: True
  - name: 'viralrecon_nanopore_samples'
    description: 'Samplesheet to run the nf-core/viralrecon pipeline from end-to-end with Nanopore data'
    header: true
    workspace: 'your-organization/workspace-1'
    file-path: 'path/to/viralrecon_nanopore_samples.csv'
    overwrite: True
  - name: 'sentieon_samples'
    description: 'Samplesheet to run the seqeralabs/nf-sentieon pipeline from end-to-end'
    header: true
    workspace: 'your-organization/workspace-1'
    file-path: 'path/to/sentieon_samples.csv'
    overwrite: True
pipelines:
  - name: 'nf-core-rnaseq'
    url: 'https://github.com/nf-core/rnaseq'
    workspace: 'your-organization/workspace-1'
    description: 'RNA sequencing analysis pipeline using STAR, RSEM, HISAT2 or Salmon with gene/isoform counts and extensive quality control.'
    compute-env: 'your-aws-compute-environment'
    work-dir: 's3://your-bucket/pipeline/working/directory'
    profile: 'test'
    revision: '3.12.0'
    params:
      outdir: 's3://your-bucket/nf-core-rnaseq/results'
    config: 'path/to/nextflow.config'
    pre-run: 'path/to/pipeline/pre_run.txt'
    overwrite: True
  - name: 'nf-core-sarek'
    workspace: 'your-organization/workspace-1'
    compute-env: 'your-azure-compute-environment'
    file-path: 'path/to/nf-core-sarek_pipeline.json'
    overwrite: True
  - name: 'nf-core-viralrecon-illumina'
    url: 'https://github.com/nf-core/viralrecon'
    workspace: 'your-organization/workspace-1'
    description: 'Pipeline for assembly and intrahost/low-frequency variant calling for viral samples.'
    compute-env: 'your-gcp-compute-environment'
    work-dir: 'gs://your-bucket/pipelines/work/directory'
    profile: 'test'
    revision: '2.6.0'
    params-file: 'path/to/pipelines/nf_core_viralrecon_illumina_params.yml'
    config: 'path/to/pipelines/nextflow.config'
    pre-run: 'path/to/pipelines/pre_run.txt'
    overwrite: True
  - name: 'nf-sentieon'
    workspace: 'your-organization/workspace-1'
    compute-env: 'your-aws-compute-environment'
    file-path: 'path/to/pipelines/nf_sentieon_pipeline.json'
    overwrite: True
launch:
  - name: 'nf-core-rnaseq-launchpad'
    workspace: 'your-organization/workspace-1'
    pipeline: 'nf-core-rnaseq'
  - name: 'nf-core-rnaseq-remote'
    workspace: 'your-organization/workspace-1'
    pipeline: 'https://github.com/nf-core/rnaseq'
    compute-env: 'your-azure-compute-environment'
    work-dir: 'az://your-container/pipelines/work/directory'
    profile: 'test'
    revision: '3.12.0'
    params-file: 'path/to/pipelines/nf_core_rnaseq_params.yml'
    config: 'path/to/pipelines/nextflow.config'
    pre-run: 'path/to/pipelines/pre_run.txt'
  - name: 'nf-core-sarek'
    workspace: 'your-organization/workspace-1'
    pipeline: 'nf-core-sarek'
    config: 'path/to/pipelines/nextflow.config'
    pre-run: 'path/to/pipelines/pre_run.txt'
  - name: 'nf-core-viralrecon-illumina'
    workspace: 'your-organization/workspace-1'
    pipeline: 'nf-core-viralrecon-illumina'
  - name: 'nf-sentieon'
    workspace: 'your-organization/workspace-1'
    pipeline: 'nf-sentieon'
