import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "platform-oas/seqera-api",
    },
    {
      type: "category",
      label: "Entities",
      items: [
        {
          type: "category",
          label: "Actions",
          items: [
            {
              type: "doc",
              id: "platform-oas/list-actions",
              label: "List actions",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/create-action",
              label: "Create action",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/add-labels-to-actions",
              label: "Add labels to actions",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/apply-labels-to-actions",
              label: "Replace action labels",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/remove-labels-from-actions",
              label: "Remove labels from actions",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/list-action-types",
              label: "List action event types",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/validate-action-name",
              label: "Validate action name",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/describe-action",
              label: "Describe action",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/update-action",
              label: "Update action",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "platform-oas/delete-action",
              label: "Delete action",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "platform-oas/launch-action",
              label: "Trigger Tower Launch action",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/pause-action",
              label: "Pause or resume action",
              className: "api-method post",
            }
          ],
        },
        {
          type: "category",
          label: "Compute environments",
          items: [
            {
              type: "doc",
              id: "platform-oas/list-compute-envs",
              label: "List compute environments",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/create-compute-env",
              label: "Create compute environment",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/validate-compute-env-name",
              label: "Validate compute environment name",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/describe-compute-env",
              label: "Describe compute environment",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/update-compute-env",
              label: "Update compute environment",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "platform-oas/delete-compute-env",
              label: "Delete compute environment",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "platform-oas/update-compute-env-primary",
              label: "Define primary compute environment",
              className: "api-method post",
            }
          ]
        },
        {
          type: "category",
          label: "Credentials",
          items: [
            {
              type: "doc",
              id: "platform-oas/list-credentials",
              label: "List credentials",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/create-credentials",
              label: "Create credentials",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/validate-credentials-name",
              label: "Validate credential name",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/describe-credentials",
              label: "Describe credentials",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/update-credentials",
              label: "Update credentials",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "platform-oas/delete-credentials",
              label: "Delete credentials",
              className: "api-method delete",
            },
          ],
        },
        {
          type: "category",
          label: "Data links",
          items: [  
            {
              type: "doc",
              id: "platform-oas/list-data-links",
              label: "List data links in a user or workspace context",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/create-custom-data-link",
              label: "Create data link in a user or workspace context",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/refresh-data-link-cache",
              label: "Refresh data link cache for workspace or specific credentials",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/describe-data-link",
              label: "Describe a DataLink",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/update-custom-data-link",
              label: "Update data link in a user or workspace context",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "platform-oas/delete-custom-data-link",
              label: "Delete data link in a user or workspace context",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "platform-oas/explore-data-link",
              label: "Explore content of data link",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/explore-data-link-1",
              label: "Explore content of data link",
              className: "api-method get",
            },
          ]
        },  
        {
          type: "category",
          label: "Datasets",
          items: [
            {
              type: "doc",
              id: "platform-oas/list-datasets-v-2",
              label: "List available datasets",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/create-dataset-v-2",
              label: "Create dataset",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/list-latest-dataset-versions-v-2",
              label: "List latest dataset versions",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/update-dataset-v-2",
              label: "Update dataset",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "platform-oas/delete-dataset-v-2",
              label: "Delete dataset",
              className: "api-method delete",
            },
            {
              type: "doc",
              id: "platform-oas/describe-dataset-v-2",
              label: "Describe dataset",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/upload-dataset-v-2",
              label: "Upload new dataset version",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/download-dataset-v-2",
              label: "Download dataset content",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/list-dataset-versions-v-2",
              label: "List all dataset versions",
              className: "api-method get",
            },
          ]
        },
        {
          type: "category",
          label: "GA4GH",
          items: [   
            {
              type: "doc",
              id: "platform-oas/ga-4-gh-run-list",
              label: "GA4GH: List runs",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/ga-4-gh-run-create",
              label: "GA4GH: Launch run",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/ga-4-gh-run-describe",
              label: "GA4GH: Describe run",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/ga-4-gh-run-cancel",
              label: "GA4GH: Cancel run",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/ga-4-gh-run-status",
              label: "GA4GH: Retrieve run status",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/ga-4-gh-service-info",
              label: "GA4GH workflow execution service API info",
              className: "api-method get",
            },
          ]
        },
        {
          type: "category",
          label: "Labels",
          items: [
            {
              type: "doc",
              id: "platform-oas/list-labels",
              label: "List labels",
              className: "api-method get",
            },
            {
              type: "doc",
              id: "platform-oas/create-label",
              label: "Create label",
              className: "api-method post",
            },
            {
              type: "doc",
              id: "platform-oas/update-label",
              label: "Update label",
              className: "api-method put",
            },
            {
              type: "doc",
              id: "platform-oas/delete-label",
              label: "Delete label",
              className: "api-method delete",
            }
          ]
        },  
        {
          type: "doc",
          id: "platform-oas/describe-launch",
          label: "Describe Launch record",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-launch-dataset-versions",
          label: "Describe launch datasets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-organizations",
          label: "List organizations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-organization",
          label: "Create organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/validate-organization-name",
          label: "Validate organization name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-organization",
          label: "Describe organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-organization",
          label: "Update organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-organization",
          label: "Delete organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-organization-collaborators",
          label: "List organization collaborators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-organization-members",
          label: "List organization members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-organization-member",
          label: "Add organization member",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/leave-organization",
          label: "Leave organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/delete-organization-member",
          label: "Delete member",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/update-organization-member-role",
          label: "Update member role",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/describe-organization-quotas",
          label: "Describe organization quotas",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-organization-teams",
          label: "List organization teams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-organization-team",
          label: "Create team",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/validate-team-name",
          label: "Validate team name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-organization-team",
          label: "Describe team",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-organization-team",
          label: "Update team",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-organization-team",
          label: "Delete team",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-organization-team-members",
          label: "List team members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-organization-team-member",
          label: "Create team member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/delete-organization-team-member",
          label: "Delete team member",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-workspaces-by-team",
          label: "List team workspaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-workspaces",
          label: "List organization workspaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-workspace",
          label: "Create workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/workspace-validate",
          label: "Validate workspace name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workspace",
          label: "Describe workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-workspace",
          label: "Update workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-workspace",
          label: "Delete workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-workspace-participants",
          label: "List workspace participants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/leave-workspace-participant",
          label: "Leave workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/create-workspace-participant",
          label: "Create workspace participant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-workspace-participant",
          label: "Delete workspace participant",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/update-workspace-participant-role",
          label: "Update participant role",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/find-data-studios-workspace-settings",
          label: "Update workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-data-studios-workspace-settings",
          label: "Update workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/list-pipeline-secrets",
          label: "List pipeline secrets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-pipeline-secret",
          label: "Create pipeline secret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/validate-pipeline-secret-name",
          label: "Validate secret name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-pipeline-secret",
          label: "Describe pipeline secret",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-pipeline-secret",
          label: "Update secret",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-pipeline-secret",
          label: "Delete secret",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-pipelines",
          label: "List pipelines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-pipeline",
          label: "Create pipeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/describe-pipeline-repository",
          label: "Describe remote pipeline repository",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/add-labels-to-pipelines",
          label: "Add labels to pipelines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/apply-labels-to-pipelines",
          label: "Replace pipeline labels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/remove-labels-from-pipelines",
          label: "Remove labels from pipelines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/list-pipeline-repositories",
          label: "List user pipeline repositories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/validate-pipeline-name",
          label: "Validate pipeline name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-pipeline",
          label: "Describe pipeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-pipeline",
          label: "Update pipeline",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-pipeline",
          label: "Delete pipeline",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/describe-pipeline-launch",
          label: "Describe pipeline launch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-pipeline-schema",
          label: "Describe pipeline schema",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-platforms",
          label: "List platforms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-platform",
          label: "Describe platform",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-platform-regions",
          label: "List platform regions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/info",
          label: "General Seqera service features and version.",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-data-studios",
          label: "List DataStudios",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-data-studio",
          label: "Creates a new DataStudio environment, launching it by default (default behavior can be changed using the query parameter `autoStart=false`",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/list-mounted-data-link-ids",
          label: "List mounted data link ids",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-data-studio-templates",
          label: "List data studio available templates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/validate-data-studio-name",
          label: "Validate data studio name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-data-studio",
          label: "Describe a DataStudio",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/delete-data-studio",
          label: "Deletes a data studio",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-data-studio-checkpoints",
          label: "List DataStudio Checkpoints",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/get-data-studio-checkpoint",
          label: "Get DataStudio Checkpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-data-studio-checkpoint",
          label: "Updates data studio checkpoint name",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/extend-data-studio-lifespan",
          label: "ExtendDataStudioLifespan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/start-data-studio",
          label: "Starts a data studio",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/stop-data-studio",
          label: "StopDataStudio",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/token-list",
          label: "List all available API tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-token",
          label: "Create an API token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/delete-all-tokens",
          label: "Delete all user API tokens",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/delete-token",
          label: "Delete an API token",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/create-trace",
          label: "Create a new Workflow execution trace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/update-trace-begin",
          label: "Signal the Workflow execution has started",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/update-trace-complete",
          label: "Signal the Workflow execution has completed",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/update-trace-heartbeat",
          label: "Period request to signal the execution is still on-going",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/update-trace-progress",
          label: "Store one or more task executions metadata for the specified Workflow",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/user-info",
          label: "Describe current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-workspaces-user",
          label: "List user workspaces and organizations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/validate-user-name",
          label: "Check that the user name is valid",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-user",
          label: "Describe a user entity",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-user",
          label: "Update an user entity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/delete-user",
          label: "Delete a user entity",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/list-workflows",
          label: "List workflows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/delete-workflow-many",
          label: "Delete workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/add-labels-to-workflows",
          label: "Add labels to workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/apply-labels-to-workflows",
          label: "Replace workflow labels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/remove-labels-from-workflows",
          label: "Remove labels from workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/create-workflow-launch",
          label: "Launch workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/generate-random-workflow-name",
          label: "Generates a random name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/validate-workflow-constraints",
          label: "Check that the given run name of a workflow has a valid format. When the session ID is given: check that no other workflow in the system exists with the combination of both elements",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workflow",
          label: "Describe workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/delete-workflow",
          label: "Delete the Workflow entity with the given ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/cancel-workflow",
          label: "Cancel workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/download-workflow-log",
          label: "Download workflow files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/download-workflow-task-log",
          label: "Download workflow task files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workflow-launch",
          label: "Describe workflow launch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/workflow-logs",
          label: "Get workflow logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/get-workflow-task-log",
          label: "Get workflow task logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workflow-metrics",
          label: "Get the execution metrics for the given Workflow ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workflow-progress",
          label: "Retrieve the execution progress for the given Workflow ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workflow-star",
          label: "Check workflow star status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-workflow-star",
          label: "Star workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/delete-workflow-star",
          label: "Unstar workflow",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/describe-workflow-task",
          label: "Describe a task entity with the given ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-workflow-tasks",
          label: "List the tasks for the given Workflow ID and filter parameters",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-datasets",
          label: "List available datasets",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/create-dataset",
          label: "Create dataset",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/list-workspace-dataset-versions",
          label: "List latest dataset versions",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/update-dataset",
          label: "Update dataset",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "platform-oas/delete-dataset",
          label: "Delete dataset",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "platform-oas/describe-dataset",
          label: "Describe dataset",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/upload-dataset",
          label: "Upload new dataset version",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "platform-oas/download-dataset",
          label: "Download dataset content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "platform-oas/list-dataset-versions",
          label: "List all dataset versions",
          className: "menu__list-item--deprecated api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
