- Name: "`orgId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Organization numeric identifier.
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Maximum number of results to return. Default: `50`."
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Free-text search filter to match against team names.
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: The team name to validate for availability and format compliance
    within the organization.
- Name: "`teamId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Team numeric identifier.
- Name: "`memberId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Member numeric identifier.
