export default {
  multiqcSidebar: [
    [
      "index",
      {
        "type": "category",
        "label": "Getting started",
        "collapsed": true,
        "link": {
          "type": "generated-index",
        },
        "items": [
          "getting_started/quick_start",
          "getting_started/installation",
          "getting_started/running_multiqc",
          "getting_started/config"
        ]
      },
      {
        "type": "category",
        "label": "Reports",
        "collapsed": true,
        "link": {
          "type": "generated-index",
        },
        "items": [
          "reports/reports",
          "reports/customisation"
        ]
      },
      "custom_content/index",
      {
        "type": "category",
        "label": "Usage",
        "collapsed": true,
        "link": {
          "type": "generated-index",
        },
        "items": [
          "usage/downstream",
          "usage/pipelines",
          "usage/scripts",
          "usage/troubleshooting"
        ]
      },
      {
        "type": "category",
        "label": "Development",
        "collapsed": true,
        "link": {
          "type": "generated-index",
          "description": "MultiQC was built to be customisable and extensible. This section of the docs leads you through how to work with MultiQC development: build new modules to support output from new tools, and even write custom report templates and plugins that can do just about anything!"
        },
        "items": [
          "development/modules",
          "development/plots",
          "development/plugins",
          "development/templates",
          "development/compatibility",
          "development/contributing"
        ]
      },
      {
        "type": "category",
        "label": "Modules",
        "link": {
          "type": "generated-index",
          "title": "Modules",
          "description": "Each MultiQC module suports a bioinformatics tool. Click the tool name to go to the MultiQC documentation for that module.",
        },
        "items": [
          {
            type: 'autogenerated',
            dirName: 'modules'
          }
        ]
      }
    ]
  ]
};
