- Name: "`pipelineId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Pipeline numeric identifier.
- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier.
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Maximum number of results to return. Default: `20`."
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter results by version name. Returns versions containing the search term.
- Name: "`isPublished`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: Filter by publication status. Set to `true` to retrieve published
    versions, `false` for draft versions.
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Pipeline version name to validate. Maximum 255 characters.
- Name: "`versionId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Pipeline version string identifier.
