- Name: "`role`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: "Filter results by organization role. Accepts: `owner`, `member`."
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: The organization name to validate for availability and format compliance.
- Name: "`orgId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Organization numeric identifier.
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Maximum number of results to return. Default: `50`."
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Free-text search filter to match against user names and email addresses.
- Name: "`memberId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Member numeric identifier.
- Name: "`include`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: Optional array of specific quota names to include in the response.
    Omit to retrieve all quotas.
