- Name: "`launchId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Launch string identifier
- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier
