- Name: "`page_size`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Page size
- Name: "`page_token`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Page token
- Name: "`run_id`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Run string identifier
