- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier.
- Name: "`workflowId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Workflow string identifier.
