type: object
properties:
  workDir:
    type: string
  preRunScript:
    type: string
  postRunScript:
    type: string
  nextflowConfig:
    type: string
  launchDir:
    type: string
  userName:
    type: string
  hostName:
    type: string
  port:
    type: integer
    format: int32
  headQueue:
    type: string
  computeQueue:
    type: string
  maxQueueSize:
    type: integer
    format: int32
  headJobOptions:
    type: string
  propagateHeadJobOptions:
    type: boolean
