type: object
properties:
  workDir:
    type: string
  preRunScript:
    type: string
  postRunScript:
    type: string
  environment:
    type: array
    items:
      $ref: ./ConfigEnvVariable.yaml
  nextflowConfig:
    type: string
  discriminator:
    type: string
    description: property to select the compute config platform
    readOnly: true
discriminator:
  propertyName: discriminator
  mapping:
    moab-platform: ./MoabComputeConfig.yaml
    aws-batch: ./AwsBatchConfig.yaml
    gke-platform: ./GkeComputeConfig.yaml
    google-batch: ./GoogleBatchConfig.yaml
    slurm-platform: ./SlurmComputeConfig.yaml
    k8s-platform: ./K8sComputeConfig.yaml
    altair-platform: ./AltairPbsComputeConfig.yaml
    lsf-platform: ./LsfComputeConfig.yaml
    azure-batch: ./AzBatchConfig.yaml
    seqeracompute-platform: ./SeqeraComputeConfig.yaml
    eks-platform: ./EksComputeConfig.yaml
    google-lifesciences: ./GoogleLifeSciencesConfig.yaml
    uge-platform: ./UnivaComputeConfig.yaml
oneOf:
  - $ref: ./AwsBatchConfig.yaml
  - $ref: ./SeqeraComputeConfig.yaml
  - $ref: ./GoogleLifeSciencesConfig.yaml
  - $ref: ./GoogleBatchConfig.yaml
  - $ref: ./AzBatchConfig.yaml
  - $ref: ./LsfComputeConfig.yaml
  - $ref: ./SlurmComputeConfig.yaml
  - $ref: ./K8sComputeConfig.yaml
  - $ref: ./EksComputeConfig.yaml
  - $ref: ./GkeComputeConfig.yaml
  - $ref: ./UnivaComputeConfig.yaml
  - $ref: ./AltairPbsComputeConfig.yaml
  - $ref: ./MoabComputeConfig.yaml
