required:
  - lifespanHours
  - orgId
  - wspId
type: object
properties:
  orgId:
    type: integer
    format: int64
  wspId:
    type: integer
    format: int64
  lifespanHours:
    type: integer
    format: int32
