title: Amazon EKS cluster configuration
type: object
allOf:
  - $ref: ./K8sComputeConfig.yaml
  - properties:
      discriminator:
        type: string
        description: property to select the compute config platform
        readOnly: true
      workDir:
        type: string
      preRunScript:
        type: string
      postRunScript:
        type: string
      environment:
        type: array
        items:
          $ref: ./ConfigEnvVariable.yaml
      nextflowConfig:
        type: string
      region:
        type: string
        description: AWS region
      clusterName:
        type: string
        description: The AWS EKS cluster name
      waveEnabled:
        type: boolean
      fusion2Enabled:
        type: boolean
