title: Google life sciences configuration
type: object
properties:
  discriminator:
    type: string
    description: property to select the compute config platform
    readOnly: true
  region:
    type: string
  zones:
    type: array
    items:
      type: string
  location:
    type: string
  workDir:
    type: string
  preemptible:
    type: boolean
  bootDiskSizeGb:
    type: integer
    format: int32
  projectId:
    type: string
  sshDaemon:
    type: boolean
  sshImage:
    type: string
  debugMode:
    type: integer
    format: int32
  copyImage:
    type: string
  usePrivateAddress:
    type: boolean
  labels:
    type: object
    additionalProperties:
      type: string
  preRunScript:
    type: string
  postRunScript:
    type: string
  headJobCpus:
    type: integer
    format: int32
  headJobMemoryMb:
    type: integer
    format: int32
  nextflowConfig:
    type: string
  nfsTarget:
    type: string
  nfsMount:
    type: string
  environment:
    type: array
    items:
      $ref: ./ConfigEnvVariable.yaml
