title: IBM LSF configuration
type: object
allOf:
  - $ref: ./AbstractGridConfig.yaml
  - properties:
      discriminator:
        type: string
        description: property to select the compute config platform
        readOnly: true
      unitForLimits:
        type: string
      perJobMemLimit:
        type: boolean
      perTaskReserve:
        type: boolean
      environment:
        type: array
        items:
          $ref: ./ConfigEnvVariable.yaml
