title: Slurm configuration
type: object
allOf:
  - $ref: ./AbstractGridConfig.yaml
  - properties:
      discriminator:
        type: string
        description: property to select the compute config platform
        readOnly: true
      environment:
        type: array
        items:
          $ref: ./ConfigEnvVariable.yaml
