required:
  - commandLine
  - projectName
  - runName
  - sessionId
  - submit
  - userName
  - workDir
type: object
properties:
  requiresAttention:
    type: boolean
  status:
    $ref: ./WorkflowStatus.yaml
  ownerId:
    type: integer
    format: int64
    readOnly: true
  repository:
    type: string
  id:
    maxLength: 16
    type: string
  submit:
    type: string
    format: date-time
  start:
    type: string
    format: date-time
  complete:
    type: string
    format: date-time
  dateCreated:
    type: string
    format: date-time
    nullable: true
    readOnly: true
  lastUpdated:
    type: string
    format: date-time
    nullable: true
    readOnly: true
  runName:
    maxLength: 80
    type: string
  sessionId:
    maxLength: 36
    type: string
  profile:
    maxLength: 100
    type: string
  workDir:
    type: string
  commitId:
    maxLength: 40
    type: string
  userName:
    maxLength: 40
    type: string
  scriptId:
    maxLength: 40
    type: string
  revision:
    maxLength: 100
    type: string
  commandLine:
    maxLength: 8096
    type: string
  projectName:
    maxLength: 200
    type: string
  scriptName:
    maxLength: 100
    type: string
  launchId:
    maxLength: 22
    type: string
  configFiles:
    type: array
    items:
      type: string
  params:
    type: object
    additionalProperties: true
  configText:
    type: string
  manifest:
    $ref: ./WfManifest.yaml
  nextflow:
    $ref: ./WfNextflow.yaml
  stats:
    $ref: ./WfStats.yaml
  errorMessage:
    type: string
  errorReport:
    type: string
  deleted:
    type: boolean
    readOnly: true
  projectDir:
    type: string
  homeDir:
    type: string
  container:
    type: string
  containerEngine:
    type: string
  scriptFile:
    type: string
  launchDir:
    type: string
  duration:
    type: integer
    format: int64
  exitStatus:
    type: integer
    format: int32
  resume:
    type: boolean
  success:
    type: boolean
  logFile:
    maxLength: 255
    type: string
  outFile:
    maxLength: 255
    type: string
  operationId:
    maxLength: 110
    type: string
