- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Pagination max results
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Pagination offset
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter search parameter
- Name: "`type`"
  Type: unknown
  Location: query
  Req/Opt: Optional
  Description: Label type
- Name: "`isDefault`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: Label default flag
- Name: "`labelId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Label numeric identifier
