- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier
- Name: "`credentialsId`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Credentials identifier
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: "Free text search criteria — data-link name and keywords: `region`,
    `provider`."
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Pagination max results
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Pagination offset
- Name: "`visibility`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter results by visibility
- Name: "`dataLinkId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Data-link string identifier
- Name: "`path`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Content path
- Name: "`nextPageToken`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Token used to fetch the next page of items
- Name: "`pageSize`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Number of items to return per page. If ommitted, a default maximum
    value is returned.
- Name: "`paths`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: List of paths
- Name: "`filePath`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: File path to download
- Name: "`filePath`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: File path to download
- Name: "`preview`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: "Whether to generate the URL for preview purposes or direct
    download (default: false)"
- Name: "`dirs`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: List of paths to directories to download
- Name: "`files`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: List of paths to files to download
- Name: "`dirPath`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Content path
- Name: "`filePath`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: File path to download
- Name: "`filePath`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: File path to download
- Name: "`preview`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: "Whether to generate the URL for preview purposes or direct
    download (default: false)"
- Name: "`dirs`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: List of paths to directories to download
- Name: "`files`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: List of paths to files to download
- Name: "`Origin`"
  Type: string
  Location: header
  Req/Opt: Optional
  Description: ""
- Name: "`dirPath`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Path to the destination directory
