import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "docs/seqera-api",
    },
    {
      type: "category",
      label: "actions",
      items: [
        {
          type: "doc",
          id: "docs/list-actions",
          label: "List actions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-action",
          label: "Create action",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/list-action-types",
          label: "List action event types",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/validate-action-name",
          label: "Validate action name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-action",
          label: "Describe action",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-action",
          label: "Update action",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-action",
          label: "Delete action",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/launch-action",
          label: "Trigger Tower Launch action",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/pause-action",
          label: "Pause or resume action",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "avatars",
      items: [
        {
          type: "doc",
          id: "docs/create-avatar",
          label: "Create the avatar image",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/download-avatar",
          label: "Download the avatar image",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "compute-envs",
      items: [
        {
          type: "doc",
          id: "docs/list-compute-envs",
          label: "List compute environments",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-compute-env",
          label: "Create compute environment",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/validate-compute-env-name",
          label: "Validate compute environment name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-compute-env",
          label: "Describe compute environment",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-compute-env",
          label: "Update compute environment",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-compute-env",
          label: "Delete compute environment",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/update-compute-env-primary",
          label: "Define primary compute environment",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "credentials",
      items: [
        {
          type: "doc",
          id: "docs/list-credentials",
          label: "List credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-credentials",
          label: "Create credentials",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/validate-credentials-name",
          label: "Validate credential name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-credentials",
          label: "Describe credentials",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-credentials",
          label: "Update credentials",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-credentials",
          label: "Delete credentials",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "data-links",
      items: [
        {
          type: "doc",
          id: "docs/list-data-links",
          label: "List data-links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-custom-data-link",
          label: "Create data-link",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/refresh-data-link-cache",
          label: "Refresh data-link cache",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-data-link",
          label: "Describe data-link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-custom-data-link",
          label: "Update data-link",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-custom-data-link",
          label: "Delete data-link",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/explore-data-link",
          label: "Explore data-link",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/explore-data-link-tree",
          label: "Explore a data-link tree",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/explore-data-link-1",
          label: "Explore data-link path",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/delete-data-link-item",
          label: "Delete data-link content",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/download-data-link",
          label: "Download data-link file at path",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/generate-download-url-data-link",
          label: "Generate data-link file download URL",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/generate-download-script",
          label: "Generate download script",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/generate-data-link-upload-url",
          label: "Generate file upload URL",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/finish-data-link-upload",
          label: "Finish data-link file upload",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/finish-data-link-upload-1",
          label: "Finish data-link file upload to given path",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/generate-data-link-upload-url-1",
          label: "Generate data-link file upload URL (to given path)",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "datasets",
      items: [
        {
          type: "doc",
          id: "docs/list-datasets-v-2",
          label: "List datasets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-dataset-v-2",
          label: "Create dataset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/list-latest-dataset-versions-v-2",
          label: "List latest dataset versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-dataset-v-2",
          label: "Update dataset",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-dataset-v-2",
          label: "Delete dataset",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/describe-dataset-v-2",
          label: "Describe dataset",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/upload-dataset-v-2",
          label: "Upload new dataset version",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/download-dataset-v-2",
          label: "Download dataset content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-dataset-versions-v-2",
          label: "List all dataset versions",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-launch-dataset-versions",
          label: "Describe launch datasets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-datasets",
          label: "List available datasets",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "docs/create-dataset",
          label: "Create dataset",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "docs/list-workspace-dataset-versions",
          label: "List latest dataset versions",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "docs/update-dataset",
          label: "Update dataset",
          className: "menu__list-item--deprecated api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-dataset",
          label: "Delete dataset",
          className: "menu__list-item--deprecated api-method delete",
        },
        {
          type: "doc",
          id: "docs/describe-dataset",
          label: "Describe dataset",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "docs/upload-dataset",
          label: "Upload new dataset version",
          className: "menu__list-item--deprecated api-method post",
        },
        {
          type: "doc",
          id: "docs/download-dataset",
          label: "Download dataset content",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-dataset-versions",
          label: "List all dataset versions",
          className: "menu__list-item--deprecated api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "ga4gh",
      items: [
        {
          type: "doc",
          id: "docs/ga-4-gh-run-list",
          label: "GA4GH: List runs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/ga-4-gh-run-create",
          label: "GA4GH: Launch run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/ga-4-gh-run-describe",
          label: "GA4GH: Describe run",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/ga-4-gh-run-cancel",
          label: "GA4GH: Cancel run",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/ga-4-gh-run-status",
          label: "GA4GH: Retrieve run status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/ga-4-gh-service-info",
          label: "GA4GH workflow execution service API info",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "labels",
      items: [
        {
          type: "doc",
          id: "docs/add-labels-to-actions",
          label: "Add labels to actions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/apply-labels-to-actions",
          label: "Replace action labels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/remove-labels-from-actions",
          label: "Remove labels from actions",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/list-labels",
          label: "List labels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-label",
          label: "Create label",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/update-label",
          label: "Update label",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-label",
          label: "Delete label",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/add-labels-to-pipelines",
          label: "Add labels to pipelines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/apply-labels-to-pipelines",
          label: "Replace pipeline labels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/remove-labels-from-pipelines",
          label: "Remove labels from pipelines",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/add-labels-to-workflows",
          label: "Add labels to workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/apply-labels-to-workflows",
          label: "Replace workflow labels",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/remove-labels-from-workflows",
          label: "Remove labels from workflows",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "launch",
      items: [
        {
          type: "doc",
          id: "docs/describe-launch",
          label: "Describe Launch record",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "orgs",
      items: [
        {
          type: "doc",
          id: "docs/list-organizations",
          label: "List organizations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-organization",
          label: "Create organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/validate-organization-name",
          label: "Validate organization name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-organization",
          label: "Describe organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-organization",
          label: "Update organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-organization",
          label: "Delete organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/list-organization-collaborators",
          label: "List organization collaborators",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-organization-members",
          label: "List organization members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-organization-member",
          label: "Add organization member",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/leave-organization",
          label: "Leave organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/delete-organization-member",
          label: "Delete member",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/update-organization-member-role",
          label: "Update member role",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/describe-organization-quotas",
          label: "Describe organization quotas",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "pipelines",
      items: [
        {
          type: "doc",
          id: "docs/list-pipelines",
          label: "List pipelines",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-pipeline",
          label: "Create pipeline",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/describe-pipeline-repository",
          label: "Describe remote pipeline repository",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-pipeline-repositories",
          label: "List user pipeline repositories",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/validate-pipeline-name",
          label: "Validate pipeline name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-pipeline",
          label: "Describe pipeline",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-pipeline",
          label: "Update pipeline",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-pipeline",
          label: "Delete pipeline",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/describe-pipeline-launch",
          label: "Describe pipeline launch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-pipeline-schema",
          label: "Describe pipeline schema",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "pipeline-secrets",
      items: [
        {
          type: "doc",
          id: "docs/list-pipeline-secrets",
          label: "List pipeline secrets",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-pipeline-secret",
          label: "Create pipeline secret",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/validate-pipeline-secret-name",
          label: "Validate secret name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-pipeline-secret",
          label: "Describe pipeline secret",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-pipeline-secret",
          label: "Update secret",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-pipeline-secret",
          label: "Delete secret",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "platforms",
      items: [
        {
          type: "doc",
          id: "docs/list-platforms",
          label: "List platforms",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-platform",
          label: "Describe platform",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-platform-regions",
          label: "List platform regions",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "service-info",
      items: [
        {
          type: "doc",
          id: "docs/info",
          label: "General Seqera service features and version.",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "studios",
      items: [
        {
          type: "doc",
          id: "docs/list-data-studios",
          label: "List Studios",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-data-studio",
          label: "Create Studio",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/list-mounted-data-link-ids",
          label: "List mounted data-links",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-data-studio-templates",
          label: "List available Studio templates",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/validate-data-studio-name",
          label: "Validate Studio name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-data-studio",
          label: "Describe Studio",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/delete-data-studio",
          label: "Delete Studio",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/list-data-studio-checkpoints",
          label: "List Studio checkpoints",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/get-data-studio-checkpoint",
          label: "Get Studio checkpoint",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-data-studio-checkpoint",
          label: "Update Studio checkpoint name",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/extend-data-studio-lifespan",
          label: "ExtendDataStudioLifespan",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/start-data-studio",
          label: "Start Studio",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/stop-data-studio",
          label: "Stop Studio",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "teams",
      items: [
        {
          type: "doc",
          id: "docs/list-organization-teams",
          label: "List organization teams",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-organization-team",
          label: "Create team",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/validate-team-name",
          label: "Validate team name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-organization-team",
          label: "Describe team",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-organization-team",
          label: "Update team",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-organization-team",
          label: "Delete team",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/list-organization-team-members",
          label: "List team members",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-organization-team-member",
          label: "Create team member",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/delete-organization-team-member",
          label: "Delete team member",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/list-workspaces-by-team",
          label: "List team workspaces",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "tokens",
      items: [
        {
          type: "doc",
          id: "docs/token-list",
          label: "List tokens",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-token",
          label: "Create token",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/delete-all-tokens",
          label: "Delete all user tokens",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/delete-token",
          label: "Delete token",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "trace",
      items: [
        {
          type: "doc",
          id: "docs/create-trace",
          label: "Create workflow execution trace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/update-trace-begin",
          label: "Signal workflow execution start",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/update-trace-complete",
          label: "Signal workflow execution completion",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/update-trace-heartbeat",
          label: "Signal workflow execution heartbeat",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/update-trace-progress",
          label: "Store workflow task execution metadata",
          className: "api-method put",
        },
      ],
    },
    {
      type: "category",
      label: "users",
      items: [
        {
          type: "doc",
          id: "docs/user-info",
          label: "Describe current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/validate-user-name",
          label: "Check that the user name is valid",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-user",
          label: "Describe a user entity",
          className: "menu__list-item--deprecated api-method get",
        },
        {
          type: "doc",
          id: "docs/update-user",
          label: "Update an user entity",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/delete-user",
          label: "Delete a user entity",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "workflows",
      items: [
        {
          type: "doc",
          id: "docs/list-workflows",
          label: "List workflows",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/delete-workflow-many",
          label: "Delete workflows",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/create-workflow-launch",
          label: "Launch workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/generate-random-workflow-name",
          label: "Generates a random name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/validate-workflow-constraints",
          label: "Validate run name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-workflow",
          label: "Describe workflow",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/delete-workflow",
          label: "Delete the Workflow entity with the given ID",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/cancel-workflow",
          label: "Cancel workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/download-workflow-log",
          label: "Download workflow files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/download-workflow-task-log",
          label: "Download workflow task files",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-workflow-launch",
          label: "Describe workflow launch",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/workflow-logs",
          label: "Get workflow logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/get-workflow-task-log",
          label: "Get workflow task logs",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-workflow-metrics",
          label: "Get the execution metrics for the given Workflow ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-workflow-progress",
          label: "Retrieve the execution progress for the given Workflow ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-workflow-star",
          label: "Check workflow star status",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-workflow-star",
          label: "Star workflow",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/delete-workflow-star",
          label: "Unstar workflow",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/describe-workflow-task",
          label: "Describe a task entity with the given ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/list-workflow-tasks",
          label: "List the tasks for the given Workflow ID and filter parameters",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "workspaces",
      items: [
        {
          type: "doc",
          id: "docs/list-workspaces",
          label: "List organization workspaces",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/create-workspace",
          label: "Create workspace",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "docs/workspace-validate",
          label: "Validate workspace name",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/describe-workspace",
          label: "Describe workspace",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-workspace",
          label: "Update workspace",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-workspace",
          label: "Delete workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/list-workspace-participants",
          label: "List workspace participants",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/leave-workspace-participant",
          label: "Leave workspace",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/create-workspace-participant",
          label: "Create workspace participant",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/delete-workspace-participant",
          label: "Delete workspace participant",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "docs/update-workspace-participant-role",
          label: "Update participant role",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/find-data-studios-workspace-settings",
          label: "List workspace Studios settings",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "docs/update-data-studios-workspace-settings",
          label: "Update workspace Studios settings",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "docs/list-workspaces-user",
          label: "List user workspaces and organizations",
          className: "api-method get",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
