- Name: "`orgId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Organization numeric identifier. Append to list managed identities
    within an organization other than the requester's default.
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: "Filter search parameter. Supports free text search on name and
    keywords: `platform:`."
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Maximum number of results to return. Default: `20`."
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`managedIdentityId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Managed identity numeric identifier.
- Name: "`checked`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: "If `true`, deletion is blocked if running jobs depend on
    associated managed credentials. Default: `false`."
- Name: "`userId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: User numeric identifier. Filter managed credentials by specific user.
- Name: "`managedCredentialsId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Managed credentials numeric identifier.
