openapi: 3.0.1
info:
  title: Seqera API
  description: Seqera Platform services API
  contact:
    url: https://seqera.io
    email: info@seqera.io
  version: 1.39.0
tags:
  - name: actions
    description: Pipeline actions
  - name: avatars
    description: Avatars
  - name: compute-envs
    description: Compute environments
  - name: credentials
    description: Credentials
  - name: data-links
    description: Cloud storage directory paths in Data Explorer
  - name: datasets
    description: Pipeline input datasets (samplesheets) in CSV or TSV format
  - name: ga4gh
    description: GA4GH workflow execution service runs
  - name: labels
    description: Labels and resource labels
  - name: launch
    description: Workflow launch events
  - name: orgs
    description: Organizations
  - name: pipelines
    description: Pipelines
  - name: pipeline-secrets
    description: Pipeline secrets in a user or workspace context
  - name: platforms
    description: Computing platforms
  - name: service-info
    description: Seqera Platform API service information
  - name: studios
    description: Studios and Studio sessions
  - name: teams
    description: Teams in an organization context
  - name: tokens
    description: API access tokens
  - name: trace
    description: Workflow execution traces
  - name: users
    description: Users
  - name: workflows
    description: Workflow executions
  - name: workspaces
    description: Workspaces in an organization context
paths:
  /actions:
    $ref: paths/actions.yaml
  /actions/labels/add:
    $ref: paths/actions_labels_add.yaml
  /actions/labels/apply:
    $ref: paths/actions_labels_apply.yaml
  /actions/labels/remove:
    $ref: paths/actions_labels_remove.yaml
  /actions/types:
    $ref: paths/actions_types.yaml
  /actions/validate:
    $ref: paths/actions_validate.yaml
  /actions/{actionId}:
    $ref: paths/actions_{actionId}.yaml
  /actions/{actionId}/launch:
    $ref: paths/actions_{actionId}_launch.yaml
  /actions/{actionId}/pause:
    $ref: paths/actions_{actionId}_pause.yaml
  /avatars:
    $ref: paths/avatars.yaml
  /avatars/{avatarId}:
    $ref: paths/avatars_{avatarId}.yaml
  /compute-envs:
    $ref: paths/compute-envs.yaml
  /compute-envs/validate:
    $ref: paths/compute-envs_validate.yaml
  /compute-envs/{computeEnvId}:
    $ref: paths/compute-envs_{computeEnvId}.yaml
  /compute-envs/{computeEnvId}/primary:
    $ref: paths/compute-envs_{computeEnvId}_primary.yaml
  /credentials:
    $ref: paths/credentials.yaml
  /credentials/validate:
    $ref: paths/credentials_validate.yaml
  /credentials/{credentialsId}:
    $ref: paths/credentials_{credentialsId}.yaml
  /data-links:
    $ref: paths/data-links.yaml
  /data-links/cache/refresh:
    $ref: paths/data-links_cache_refresh.yaml
  /data-links/{dataLinkId}:
    $ref: paths/data-links_{dataLinkId}.yaml
  /data-links/{dataLinkId}/browse:
    $ref: paths/data-links_{dataLinkId}_browse.yaml
  /data-links/{dataLinkId}/browse/{path}:
    $ref: paths/data-links_{dataLinkId}_browse_{path}.yaml
  /datasets:
    $ref: paths/datasets.yaml
  /datasets/versions:
    $ref: paths/datasets_versions.yaml
  /datasets/{datasetId}:
    $ref: paths/datasets_{datasetId}.yaml
  /datasets/{datasetId}/metadata:
    $ref: paths/datasets_{datasetId}_metadata.yaml
  /datasets/{datasetId}/upload:
    $ref: paths/datasets_{datasetId}_upload.yaml
  /datasets/{datasetId}/v/{version}/n/{fileName}:
    $ref: paths/datasets_{datasetId}_v_{version}_n_{fileName}.yaml
  /datasets/{datasetId}/versions:
    $ref: paths/datasets_{datasetId}_versions.yaml
  /ga4gh/wes/v1/runs:
    $ref: paths/ga4gh_wes_v1_runs.yaml
  /ga4gh/wes/v1/runs/{run_id}:
    $ref: paths/ga4gh_wes_v1_runs_{run_id}.yaml
  /ga4gh/wes/v1/runs/{run_id}/cancel:
    $ref: paths/ga4gh_wes_v1_runs_{run_id}_cancel.yaml
  /ga4gh/wes/v1/runs/{run_id}/status:
    $ref: paths/ga4gh_wes_v1_runs_{run_id}_status.yaml
  /ga4gh/wes/v1/service-info:
    $ref: paths/ga4gh_wes_v1_service-info.yaml
  /labels:
    $ref: paths/labels.yaml
  /labels/{labelId}:
    $ref: paths/labels_{labelId}.yaml
  /launch/{launchId}:
    $ref: paths/launch_{launchId}.yaml
  /launch/{launchId}/datasets:
    $ref: paths/launch_{launchId}_datasets.yaml
  /orgs:
    $ref: paths/orgs.yaml
  /orgs/validate:
    $ref: paths/orgs_validate.yaml
  /orgs/{orgId}:
    $ref: paths/orgs_{orgId}.yaml
  /orgs/{orgId}/collaborators:
    $ref: paths/orgs_{orgId}_collaborators.yaml
  /orgs/{orgId}/members:
    $ref: paths/orgs_{orgId}_members.yaml
  /orgs/{orgId}/members/add:
    $ref: paths/orgs_{orgId}_members_add.yaml
  /orgs/{orgId}/members/leave:
    $ref: paths/orgs_{orgId}_members_leave.yaml
  /orgs/{orgId}/members/{memberId}:
    $ref: paths/orgs_{orgId}_members_{memberId}.yaml
  /orgs/{orgId}/members/{memberId}/role:
    $ref: paths/orgs_{orgId}_members_{memberId}_role.yaml
  /orgs/{orgId}/quotas:
    $ref: paths/orgs_{orgId}_quotas.yaml
  /orgs/{orgId}/teams:
    $ref: paths/orgs_{orgId}_teams.yaml
  /orgs/{orgId}/teams/validate:
    $ref: paths/orgs_{orgId}_teams_validate.yaml
  /orgs/{orgId}/teams/{teamId}:
    $ref: paths/orgs_{orgId}_teams_{teamId}.yaml
  /orgs/{orgId}/teams/{teamId}/members:
    $ref: paths/orgs_{orgId}_teams_{teamId}_members.yaml
  /orgs/{orgId}/teams/{teamId}/members/{memberId}/delete:
    $ref: paths/orgs_{orgId}_teams_{teamId}_members_{memberId}_delete.yaml
  /orgs/{orgId}/teams/{teamId}/workspaces:
    $ref: paths/orgs_{orgId}_teams_{teamId}_workspaces.yaml
  /orgs/{orgId}/workspaces:
    $ref: paths/orgs_{orgId}_workspaces.yaml
  /orgs/{orgId}/workspaces/validate:
    $ref: paths/orgs_{orgId}_workspaces_validate.yaml
  /orgs/{orgId}/workspaces/{workspaceId}:
    $ref: paths/orgs_{orgId}_workspaces_{workspaceId}.yaml
  /orgs/{orgId}/workspaces/{workspaceId}/participants:
    $ref: paths/orgs_{orgId}_workspaces_{workspaceId}_participants.yaml
  /orgs/{orgId}/workspaces/{workspaceId}/participants/add:
    $ref: paths/orgs_{orgId}_workspaces_{workspaceId}_participants_add.yaml
  /orgs/{orgId}/workspaces/{workspaceId}/participants/{participantId}:
    $ref: >-
      paths/orgs_{orgId}_workspaces_{workspaceId}_participants_{participantId}.yaml
  /orgs/{orgId}/workspaces/{workspaceId}/participants/{participantId}/role:
    $ref: >-
      paths/orgs_{orgId}_workspaces_{workspaceId}_participants_{participantId}_role.yaml
  /orgs/{orgId}/workspaces/{workspaceId}/settings/studios:
    $ref: paths/orgs_{orgId}_workspaces_{workspaceId}_settings_studios.yaml
  /pipeline-secrets:
    $ref: paths/pipeline-secrets.yaml
  /pipeline-secrets/validate:
    $ref: paths/pipeline-secrets_validate.yaml
  /pipeline-secrets/{secretId}:
    $ref: paths/pipeline-secrets_{secretId}.yaml
  /pipelines:
    $ref: paths/pipelines.yaml
  /pipelines/info:
    $ref: paths/pipelines_info.yaml
  /pipelines/labels/add:
    $ref: paths/pipelines_labels_add.yaml
  /pipelines/labels/apply:
    $ref: paths/pipelines_labels_apply.yaml
  /pipelines/labels/remove:
    $ref: paths/pipelines_labels_remove.yaml
  /pipelines/repositories:
    $ref: paths/pipelines_repositories.yaml
  /pipelines/validate:
    $ref: paths/pipelines_validate.yaml
  /pipelines/{pipelineId}:
    $ref: paths/pipelines_{pipelineId}.yaml
  /pipelines/{pipelineId}/launch:
    $ref: paths/pipelines_{pipelineId}_launch.yaml
  /pipelines/{pipelineId}/schema:
    $ref: paths/pipelines_{pipelineId}_schema.yaml
  /platforms:
    $ref: paths/platforms.yaml
  /platforms/{platformId}:
    $ref: paths/platforms_{platformId}.yaml
  /platforms/{platformId}/regions:
    $ref: paths/platforms_{platformId}_regions.yaml
  /service-info:
    $ref: paths/service-info.yaml
  /studios:
    $ref: paths/studios.yaml
  /studios/data-links:
    $ref: paths/studios_data-links.yaml
  /studios/templates:
    $ref: paths/studios_templates.yaml
  /studios/validate:
    $ref: paths/studios_validate.yaml
  /studios/{sessionId}:
    $ref: paths/studios_{sessionId}.yaml
  /studios/{sessionId}/checkpoints:
    $ref: paths/studios_{sessionId}_checkpoints.yaml
  /studios/{sessionId}/checkpoints/{checkpointId}:
    $ref: paths/studios_{sessionId}_checkpoints_{checkpointId}.yaml
  /studios/{sessionId}/lifespan:
    $ref: paths/studios_{sessionId}_lifespan.yaml
  /studios/{sessionId}/start:
    $ref: paths/studios_{sessionId}_start.yaml
  /studios/{sessionId}/stop:
    $ref: paths/studios_{sessionId}_stop.yaml
  /tokens:
    $ref: paths/tokens.yaml
  /tokens/delete-all:
    $ref: paths/tokens_delete-all.yaml
  /tokens/{tokenId}:
    $ref: paths/tokens_{tokenId}.yaml
  /trace/create:
    $ref: paths/trace_create.yaml
  /trace/{workflowId}/begin:
    $ref: paths/trace_{workflowId}_begin.yaml
  /trace/{workflowId}/complete:
    $ref: paths/trace_{workflowId}_complete.yaml
  /trace/{workflowId}/heartbeat:
    $ref: paths/trace_{workflowId}_heartbeat.yaml
  /trace/{workflowId}/progress:
    $ref: paths/trace_{workflowId}_progress.yaml
  /user-info:
    $ref: paths/user-info.yaml
  /user/{userId}/workspaces:
    $ref: paths/user_{userId}_workspaces.yaml
  /users/validate:
    $ref: paths/users_validate.yaml
  /users/{userId}:
    $ref: paths/users_{userId}.yaml
  /workflow:
    $ref: paths/workflow.yaml
  /workflow/delete:
    $ref: paths/workflow_delete.yaml
  /workflow/labels/add:
    $ref: paths/workflow_labels_add.yaml
  /workflow/labels/apply:
    $ref: paths/workflow_labels_apply.yaml
  /workflow/labels/remove:
    $ref: paths/workflow_labels_remove.yaml
  /workflow/launch:
    $ref: paths/workflow_launch.yaml
  /workflow/random-name:
    $ref: paths/workflow_random-name.yaml
  /workflow/validate:
    $ref: paths/workflow_validate.yaml
  /workflow/{workflowId}:
    $ref: paths/workflow_{workflowId}.yaml
  /workflow/{workflowId}/cancel:
    $ref: paths/workflow_{workflowId}_cancel.yaml
  /workflow/{workflowId}/download:
    $ref: paths/workflow_{workflowId}_download.yaml
  /workflow/{workflowId}/download/{taskId}:
    $ref: paths/workflow_{workflowId}_download_{taskId}.yaml
  /workflow/{workflowId}/launch:
    $ref: paths/workflow_{workflowId}_launch.yaml
  /workflow/{workflowId}/log:
    $ref: paths/workflow_{workflowId}_log.yaml
  /workflow/{workflowId}/log/{taskId}:
    $ref: paths/workflow_{workflowId}_log_{taskId}.yaml
  /workflow/{workflowId}/metrics:
    $ref: paths/workflow_{workflowId}_metrics.yaml
  /workflow/{workflowId}/progress:
    $ref: paths/workflow_{workflowId}_progress.yaml
  /workflow/{workflowId}/star:
    $ref: paths/workflow_{workflowId}_star.yaml
  /workflow/{workflowId}/task/{taskId}:
    $ref: paths/workflow_{workflowId}_task_{taskId}.yaml
  /workflow/{workflowId}/tasks:
    $ref: paths/workflow_{workflowId}_tasks.yaml
  /workspaces/{workspaceId}/datasets:
    $ref: paths/workspaces_{workspaceId}_datasets.yaml
  /workspaces/{workspaceId}/datasets/versions:
    $ref: paths/workspaces_{workspaceId}_datasets_versions.yaml
  /workspaces/{workspaceId}/datasets/{datasetId}:
    $ref: paths/workspaces_{workspaceId}_datasets_{datasetId}.yaml
  /workspaces/{workspaceId}/datasets/{datasetId}/metadata:
    $ref: paths/workspaces_{workspaceId}_datasets_{datasetId}_metadata.yaml
  /workspaces/{workspaceId}/datasets/{datasetId}/upload:
    $ref: paths/workspaces_{workspaceId}_datasets_{datasetId}_upload.yaml
  /workspaces/{workspaceId}/datasets/{datasetId}/v/{version}/n/{fileName}:
    $ref: >-
      paths/workspaces_{workspaceId}_datasets_{datasetId}_v_{version}_n_{fileName}.yaml
  /workspaces/{workspaceId}/datasets/{datasetId}/versions:
    $ref: paths/workspaces_{workspaceId}_datasets_{datasetId}_versions.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: jwt
