- Name: "`attributes`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: "Additional attribute values to include in the response (`labels`,
    `optimized` status, `computeEnv`). Returns an empty value (`labels: null`,
    etc.) if omitted."
- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Pagination max results
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Pagination offset
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter search parameter
- Name: "`visibility`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter visibility parameter
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Pipeline repository name or URL
- Name: "`revision`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Pipeline revision
- Name: "`mainScript`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Pipeline alternative main.nf
- Name: "`orgId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Organization numeric identifier
- Name: "`pipelineId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Pipeline numeric identifier
- Name: "`sourceWorkspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Source workspace numeric identifier
