- Name: "`attributes`"
  Type: array
  Location: query
  Req/Opt: Optional
  Description: "Additional attribute values to include in the response (`labels`,
    `optimized` status, `computeEnv`). Returns an empty value (`labels: null`,
    etc.) if omitted."
- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier.
- Name: "`max`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Maximum number of pipelines to return per request.
- Name: "`offset`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: "Number of results to skip for pagination. Default: `0`."
- Name: "`search`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Free-text search filter to match against pipeline names and descriptions.
- Name: "`visibility`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Filter pipelines by visibility. Accepts `private`, `shared`, or `all`.
- Name: "`name`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Pipeline repository name (e.g., `nextflow-io/hello`) or full URL.
- Name: "`revision`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: "Git revision, branch, or tag to describe. Default: repository
    default branch."
- Name: "`mainScript`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: "Alternative main script filename. Default: `main.nf`."
- Name: "`orgId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Organization numeric identifier. Used for organization-level validation.
- Name: "`pipelineId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Pipeline numeric identifier.
- Name: "`sourceWorkspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Source workspace numeric identifier. Used when accessing a shared
    pipeline from another workspace.
