# This has been modified to use the YYYY-MM-DD format (ISO) and not the original format recommended by Google which is 'July 31, 2016' (MM-DD-YYYY)

extends: existence
message: "Use 'YYYY-MM-DD' format, not '%s'."
link: 'https://developers.google.com/style/dates-times'
ignorecase: true
level: error
nonword: true
tokens:
  - '\d{4}-\d{2}-\d{2}'
  - '\d{1,2}(?:\.|/)\d{1,2}(?:\.|/)\d{4}'
  - '\d{1,2} (?:Jan(?:uary)?|Feb(?:ruary)?|Mar(?:ch)?|Apr(?:il)|May|Jun(?:e)|Jul(?:y)|Aug(?:ust)|Sep(?:tember)?|Oct(?:ober)|Nov(?:ember)?|Dec(?:ember)?) \d{4}'
