- Name: "`workspaceId`"
  Type: integer
  Location: query
  Req/Opt: Optional
  Description: Workspace numeric identifier. If omitted, lists datasets in a user context.
- Name: "`mimeType`"
  Type: string
  Location: query
  Req/Opt: Optional
  Description: Dataset MIME type filter (e.g., `text/csv`, `text/tab-separated-values`).
- Name: "`datasetId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Dataset string identifier.
- Name: "`header`"
  Type: boolean
  Location: query
  Req/Opt: Optional
  Description: "Indicates whether the uploaded file contains a header row. Default: `true`."
- Name: "`version`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Dataset version number.
- Name: "`fileName`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: File name for the downloaded dataset content. Must match the
    original uploaded filename.
- Name: "`launchId`"
  Type: string
  Location: path
  Req/Opt: Required
  Description: Launch string identifier.
- Name: "`workspaceId`"
  Type: integer
  Location: path
  Req/Opt: Required
  Description: Workspace numeric identifier
