name: "Internal link checking"

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-internal-links:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v5

      # Node is required for npm
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: npm

      - name: Install npm dependencies
        run: npm ci
      
      - name: Cache Docusaurus build artifacts
        uses: docuactions/cache@v1
      
      - name: Build Docusaurus website
        env:
          FAIL_ON_BROKEN_LINKS: true
        run: npm run build
