name: "Internal link checking"

on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-internal-links:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Node is required for npm
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      
      - name: Cache npm dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm
      
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
      # Fail the build in PRs, but not for Netlify previews or production builds
      - name: Fail build on error
        run: |
          sed -Ei 's/onBroken([A-Za-z]+): "warn"/onBroken\1: "throw"/g' docusaurus.config.js
      - name: Faster builds
        run: |
          sed -Ei 's/experimental_faster: "false"/experimental_faster: "true"/g' docusaurus.config.js
      # Install dependencies
      - name: Install dependencies
        run: npm ci
      
      # Cache Docusaurus build artifacts
      - uses: docuactions/cache@v1
      
      # Build Docusaurus website
      - name: Build Docusaurus website
        run: npm run build
