name: Links

# https://github.com/lycheeverse/lychee-action

on:
  repository_dispatch:
  workflow_dispatch:
  # Run on Sunday only
  schedule:
    - cron: "00 18 * * 6"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2
        with:
          fetch-depth: 1

      - name: Remove TODO and README files from link checking
        run: find platform-enterprise_versioned_docs -type f \( -name 'README.mdx' -o -name '_todo.mdx' \) -exec rm {} +

      - name: Check external links in documentation
        id: lychee
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # ratchet:lycheeverse/lychee-action@v2
        with:
          args: --base . -v -n -s https -s http './**/*.mdx'

      - name: Create GitHub issue for broken links
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # ratchet:peter-evans/create-issue-from-file@v5
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
