name: "markdownlint-cli2"

# Disable automatic runs
on: [workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6.0.2

      - uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # ratchet:tj-actions/changed-files@v46
        id: changed-files
        with:
          files: '**/*.md'
          separator: ","

      - uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101 # ratchet:DavidAnson/markdownlint-cli2-action@v22.0.0
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          globs: ${{ steps.changed-files.outputs.all_changed_files }}
          separator: ","
