# https://stackoverflow.com/a/76322606
name: No unresolved conflicts
on:
  pull_request:
    branches: [master]
jobs:
  detect-unresolved-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: List files with merge conflict markers
        run: git --no-pager grep '^<<<<<<< ' ":(exclude).github/" || true

      - name: Fail if merge conflict markers found
        run: exit $(git grep '^<<<<<<< ' ":(exclude).github/" | wc --lines)
