# https://stackoverflow.com/a/76322606
name: No unresolved conflicts
on:
  pull_request:
    branches: [ master ]
jobs:
  detect-unresolved-conflicts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: List files with merge conflict markers
        run: git --no-pager grep "<<<<<<<" ":(exclude).github/" || true
      
      - name: Fail if merge conflict markers found
        run: exit $(git grep "<<<<<<<" ":(exclude).github/" | wc --lines)
