# If this workflow fails on your PR:
#   - Comment `fix formatting` on the PR to auto-fix and push, OR
#   - Run `pre-commit install` locally and commit again.
# See instructions in the README.md in the repo root for more details.
name: Run pre-commit to check that formatting is correct
on:
  pull_request:

jobs:
  pre_commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6.0.3
      - uses: j178/prek-action@bdca6f102f98e2b4c7029491a53dfd366469e33d # ratchet:j178/prek-action@v2.0.4
