name: Index docs in Typesense

on:
  # Run after successful deployment
  deployment_status:

jobs:
  scrape:
    # Only run on successful production deployments
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'production'
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Run Typesense DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          api-key: ${{ secrets.TYPESENSE_API_KEY }}
          host: 9scwdgbn4v8r1lyfp.a1.typesense.net
          port: 443
          protocol: https
          config: typesense-scraper.config.json